# Generated by Django 5.1.6 on 2025-02-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.TextField(max_length=15),
        ),
    ]
