# Generated by Django 5.1.6 on 2025-02-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tution", "0002_alter_contact_email_alter_contact_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("salary", models.IntegerField()),
                ("details", models.TextField()),
                ("available", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("teacher", "Teacher"), ("student", "Student")],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
