# Generated by Django 5.1.6 on 2025-02-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tution", "0003_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(
                default=models.CharField(max_length=100), max_length=100
            ),
        ),
    ]
