# Generated by Django 5.1.6 on 2025-02-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tution", "0005_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="tution/images"),
        ),
    ]
