# Generated by Django 5.1.6 on 2025-02-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LearnForms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnotherModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=20)),
                ("lname", models.CharField(max_length=20)),
                ("roll", models.IntegerField()),
                ("address", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=20)),
            ],
        ),
    ]
