# Generated by Django 5.1.6 on 2025-02-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LearnModels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=20)),
                ("lname", models.CharField(max_length=20)),
                ("mob", models.CharField(max_length=10)),
                ("job", models.CharField(max_length=20)),
            ],
        ),
    ]
