# Generated by Django 5.1.6 on 2025-02-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LearnModels", "0002_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unique_Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("roll_number", models.IntegerField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("course", models.CharField(max_length=100)),
            ],
        ),
    ]
